pipeline {
    agent any

    environment {
        // Set the name of the WAR file as generated by Maven
        WAR_NAME = "MavenWebAppJenkinsIntegrationusingAnsible.war"
        // Set the full path to the WAR file
        WAR_PATH = "target/${env.WAR_NAME}"
    }

    stages {
        stage('Checkout Code') {
            steps {
                echo "Checking out source code..."
                checkout scm
            }
        }

        stage('Build with Maven') {
            steps {
                echo "Building the project with Maven..."
                sh 'mvn clean install'
            }
        }

        stage('Verify WAR File') {
            steps {
                echo "Checking if WAR file exists at: ${env.WAR_PATH}"
                script {
                    if (!fileExists(env.WAR_PATH)) {
                        error "WAR file not found at ${env.WAR_PATH}"
                    }
                }
            }
        }

        stage('Deploy using Ansible') {
            steps {
                echo "Deploying using Ansible..."
                sh """
                    ansible-playbook -i hosts.ini playbook.yml --extra-vars "war_file=${env.WAR_PATH}"
                """
            }
        }

        stage('Archive Artifacts') {
            steps {
                echo "Archiving WAR file..."
                archiveArtifacts artifacts: "${env.WAR_PATH}", fingerprint: true
            }
        }
    }

    post {
        success {
            echo "Pipeline completed successfully!"
        }
        failure {
            echo "Pipeline failed. Check logs for details."
        }
    }
}
